apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-csharp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecast-csharp
    apps.tanzu.vmware.com/use-scanner: trivy
    apps.tanzu.vmware.com/has-tests: "true"
    foo: "bar1"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/huginmuninraven/weather-forecast
      ref:
        branch: main