apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    apps.tanzu.vmware.com/pipeline: test
  name: developer-defined-tekton-pipeline
  namespace: weather-forecast
spec:
  params:
    - default: git-credentials
      description: name of the secret holding the gitlab_pat
      name: git-credentials
      type: string
    - name: source-url                        # (!) required
    - name: source-revision                   # (!) required
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: busybox:latest
            onError: continue
            script: |-
              echo "hello world"
